services:
  ssh-server:
    image: mroranger/ssh-server:1.8
    build:
      context: .
      dockerfile: ssh.dockerfile
    container_name: ssh-server
    env_file:
      - .env
    ports:
      - "2222:22"
    volumes:
      - type: bind
        source: /Users/edooranger/Lavoro/SSH/logs/sshd.log
        target: /var/log/sshd.log
        read_only: true
    restart: unless-stopped