name: "test"

services:
  ssh-server:
    image: mroranger/ssh-server:${IMAGE_TAG:-latest}
    restart: unless-stopped
    container_name: ssh-server
    build:
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
      context: .
      dockerfile: ssh.dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT:-2222}:22"
    volumes:
      - type: bind
        source: /Users/edooranger/Lavoro/SSH/logs/sshd.log
        target: /var/log/sshd.log
        read_only: true